import type { 
  Item, 
  Source, 
  RawPricePoint, 
  UnitStandard, 
  UnitConversion,
  DataConnector,
  BasketTemplate,
  ConfidenceScore
} from './types'

export const UNIT_CONVERSIONS: UnitConversion[] = [
  { fromUnit: 'lb', toUnit: 'oz', factor: 16 },
  { fromUnit: 'oz', toUnit: 'lb', factor: 0.0625 },
  { fromUnit: 'lb', toUnit: 'kg', factor: 0.453592 },
  { fromUnit: 'kg', toUnit: 'lb', factor: 2.20462 },
  { fromUnit: 'gallon', toUnit: 'liter', factor: 3.78541 },
  { fromUnit: 'liter', toUnit: 'gallon', factor: 0.264172 },
  { fromUnit: 'therm', toUnit: 'kWh', factor: 29.3001 },
  { fromUnit: 'ccf', toUnit: 'therm', factor: 1.0307 },
]

export const EXPANDED_SOURCES: Source[] = [
  {
    id: 'usda-ams',
    name: 'USDA Agricultural Marketing Service - National Dairy & Protein Reports',
    provider: 'U.S. Department of Agriculture',
    license: 'Public Domain (U.S. Government Work)',
    terms: 'Data provided as-is for informational purposes. USDA does not guarantee accuracy.',
    url: 'https://www.ams.usda.gov/market-news/dairy',
    retrievalTimestamp: new Date().toISOString(),
    isOfficial: true,
    reliabilityTier: 'tier-1',
    refreshSchedule: 'daily',
    coverageMap: {
      'US-National': ['eggs-dozen', 'milk-gallon', 'butter-lb', 'cheese-lb', 'chicken-breast-lb', 'whole-chicken-lb'],
      'US-Midwest': ['eggs-dozen', 'milk-gallon'],
      'US-Northeast': ['milk-gallon', 'cheese-lb'],
    },
    seriesIdentifiers: ['DA_RF100', 'DA_RF110', 'DA_RF120'],
    status: 'active',
    lastSuccessfulFetch: new Date().toISOString(),
  },
  {
    id: 'usda-nass',
    name: 'USDA National Agricultural Statistics Service - Commodity Prices',
    provider: 'U.S. Department of Agriculture',
    license: 'Public Domain (U.S. Government Work)',
    terms: 'Official USDA statistics. Free to use and redistribute.',
    url: 'https://www.nass.usda.gov/Charts_and_Maps/Agricultural_Prices/',
    retrievalTimestamp: new Date().toISOString(),
    isOfficial: true,
    reliabilityTier: 'tier-1',
    refreshSchedule: 'daily',
    coverageMap: {
      'US-National': ['ground-beef-lb', 'pork-chops-lb', 'bacon-lb', 'potatoes-lb', 'onions-lb', 'tomatoes-lb', 'apples-lb', 'bananas-lb', 'seeds-packet', 'fertilizer-lb', 'feed-animal-lb'],
    },
    seriesIdentifiers: ['NASS_BEEF_01', 'NASS_PORK_01', 'NASS_PRODUCE_01'],
    status: 'active',
    lastSuccessfulFetch: new Date().toISOString(),
  },
  {
    id: 'eia-petroleum',
    name: 'EIA Petroleum Marketing Monthly',
    provider: 'U.S. Energy Information Administration',
    license: 'Public Domain (U.S. Government Work)',
    terms: 'EIA provides energy data as a public service. Data is free to use.',
    url: 'https://www.eia.gov/petroleum/marketing/monthly/',
    retrievalTimestamp: new Date().toISOString(),
    isOfficial: true,
    reliabilityTier: 'tier-1',
    refreshSchedule: 'daily',
    coverageMap: {
      'US-National': ['gasoline-gallon', 'diesel-gallon', 'heating-oil-gallon', 'propane-gallon'],
      'US-Northeast': ['heating-oil-gallon', 'propane-gallon'],
      'US-Midwest': ['gasoline-gallon', 'diesel-gallon'],
    },
    seriesIdentifiers: ['PET.EMM_EPM0_PTE_NUS_DPG.M', 'PET.EMM_EPM0D_PTE_NUS_DPG.M'],
    status: 'active',
    lastSuccessfulFetch: new Date().toISOString(),
  },
  {
    id: 'eia-natural-gas',
    name: 'EIA Natural Gas Navigator',
    provider: 'U.S. Energy Information Administration',
    license: 'Public Domain (U.S. Government Work)',
    terms: 'Official federal energy statistics available for public use.',
    url: 'https://www.eia.gov/dnav/ng/ng_pri_sum_dcu_nus_m.htm',
    retrievalTimestamp: new Date().toISOString(),
    isOfficial: true,
    reliabilityTier: 'tier-1',
    refreshSchedule: 'daily',
    coverageMap: {
      'US-National': ['natural-gas-therm', 'natural-gas-ccf'],
    },
    seriesIdentifiers: ['NG.N3020US3.M'],
    status: 'active',
    lastSuccessfulFetch: new Date().toISOString(),
  },
  {
    id: 'eia-electricity',
    name: 'EIA Electric Power Monthly',
    provider: 'U.S. Energy Information Administration',
    license: 'Public Domain (U.S. Government Work)',
    terms: 'Free access to official U.S. electricity price data.',
    url: 'https://www.eia.gov/electricity/monthly/',
    retrievalTimestamp: new Date().toISOString(),
    isOfficial: true,
    reliabilityTier: 'tier-1',
    refreshSchedule: 'daily',
    coverageMap: {
      'US-National': ['electricity-kWh'],
      'US-Residential': ['electricity-kWh'],
    },
    seriesIdentifiers: ['ELEC.PRICE.US-RES.M'],
    status: 'active',
    lastSuccessfulFetch: new Date().toISOString(),
  },
  {
    id: 'bls-wage',
    name: 'Bureau of Labor Statistics - Wage Data',
    provider: 'U.S. Department of Labor',
    license: 'Public Domain (U.S. Government Work)',
    terms: 'Official BLS wage statistics available for public use.',
    url: 'https://www.bls.gov/cew/',
    retrievalTimestamp: new Date().toISOString(),
    isOfficial: true,
    reliabilityTier: 'tier-1',
    refreshSchedule: 'daily',
    coverageMap: {
      'US-National': ['minimum-wage', 'median-wage'],
    },
    seriesIdentifiers: ['CES0500000003'],
    status: 'active',
    lastSuccessfulFetch: new Date().toISOString(),
  },
  {
    id: 'bls-cpi',
    name: 'Bureau of Labor Statistics - Consumer Price Index',
    provider: 'U.S. Department of Labor',
    license: 'Public Domain (U.S. Government Work)',
    terms: 'Official CPI published by BLS. Free for all uses.',
    url: 'https://www.bls.gov/cpi/',
    retrievalTimestamp: new Date().toISOString(),
    isOfficial: true,
    reliabilityTier: 'tier-1',
    refreshSchedule: 'daily',
    coverageMap: {
      'US-National': ['cpi-all-items', 'cpi-food', 'cpi-energy'],
    },
    seriesIdentifiers: ['CUUR0000SA0'],
    status: 'active',
    lastSuccessfulFetch: new Date().toISOString(),
  },
  {
    id: 'fred-housing',
    name: 'FRED Economic Data - Housing & Rent Indices',
    provider: 'Federal Reserve Bank of St. Louis',
    license: 'Public Domain (Federal Reserve Data)',
    terms: 'FRED data is free for public use with attribution.',
    url: 'https://fred.stlouisfed.org/',
    retrievalTimestamp: new Date().toISOString(),
    isOfficial: true,
    reliabilityTier: 'tier-1',
    refreshSchedule: 'daily',
    coverageMap: {
      'US-National': ['rent-index'],
    },
    seriesIdentifiers: ['CUSR0000SEHA'],
    status: 'active',
    lastSuccessfulFetch: new Date().toISOString(),
  },
]

export const EXPANDED_ITEMS: Item[] = [
  {
    id: 'eggs-dozen',
    name: 'Eggs',
    category: 'dairy',
    unitStandard: 'dozen',
    acceptableAlternateUnits: ['count'],
    conversions: [{ fromUnit: 'count', toUnit: 'dozen', factor: 1 / 12 }],
    description: 'Grade A large eggs',
    synonyms: ['chicken eggs', 'hen eggs'],
    sourceSeriesIds: ['usda-ams'],
    regionCoverage: ['US-National', 'US-Midwest', 'US-Northeast', 'US-South', 'US-West'],
  },
  {
    id: 'milk-gallon',
    name: 'Milk',
    category: 'dairy',
    unitStandard: 'gallon',
    acceptableAlternateUnits: ['liter'],
    conversions: [{ fromUnit: 'liter', toUnit: 'gallon', factor: 0.264172 }],
    description: 'Whole milk, conventional',
    synonyms: ['whole milk', 'fluid milk'],
    sourceSeriesIds: ['usda-ams'],
    regionCoverage: ['US-National', 'US-Midwest', 'US-Northeast', 'US-South', 'US-West'],
  },
  {
    id: 'butter-lb',
    name: 'Butter',
    category: 'dairy',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Salted butter',
    synonyms: ['dairy butter'],
    sourceSeriesIds: ['usda-ams'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'cheese-lb',
    name: 'Cheese',
    category: 'dairy',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Cheddar cheese',
    synonyms: ['cheddar', 'block cheese'],
    sourceSeriesIds: ['usda-ams'],
    regionCoverage: ['US-National', 'US-Northeast'],
  },
  {
    id: 'bread-loaf',
    name: 'Bread',
    category: 'staples',
    unitStandard: 'count',
    acceptableAlternateUnits: ['lb'],
    conversions: [{ fromUnit: 'count', toUnit: 'lb', factor: 1.5 }],
    description: 'White bread, 20 oz loaf',
    synonyms: ['white bread', 'sandwich bread', 'loaf'],
    sourceSeriesIds: ['bls-cpi'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'rice-lb',
    name: 'Rice',
    category: 'grains',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Long grain white rice',
    synonyms: ['white rice', 'grain rice'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'pasta-lb',
    name: 'Pasta',
    category: 'grains',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Dried pasta, spaghetti or macaroni',
    synonyms: ['spaghetti', 'macaroni', 'noodles'],
    sourceSeriesIds: ['bls-cpi'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'flour-lb',
    name: 'Flour',
    category: 'staples',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'All-purpose white flour',
    synonyms: ['all-purpose flour', 'wheat flour', 'baking flour'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'sugar-lb',
    name: 'Sugar',
    category: 'staples',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Granulated white sugar',
    synonyms: ['white sugar', 'granulated sugar'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'salt-lb',
    name: 'Salt',
    category: 'staples',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz'],
    conversions: [{ fromUnit: 'oz', toUnit: 'lb', factor: 0.0625 }],
    description: 'Table salt, iodized',
    synonyms: ['table salt', 'iodized salt'],
    sourceSeriesIds: ['bls-cpi'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'coffee-lb',
    name: 'Coffee',
    category: 'staples',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Ground coffee, 100% arabica',
    synonyms: ['ground coffee', 'coffee beans'],
    sourceSeriesIds: ['bls-cpi'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'chicken-breast-lb',
    name: 'Chicken Breast',
    category: 'proteins',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Boneless, skinless chicken breast',
    synonyms: ['chicken', 'poultry breast'],
    sourceSeriesIds: ['usda-ams'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'whole-chicken-lb',
    name: 'Whole Chicken',
    category: 'proteins',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Whole fryer/roaster chicken',
    synonyms: ['whole bird', 'fryer chicken'],
    sourceSeriesIds: ['usda-ams'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'ground-beef-lb',
    name: 'Ground Beef',
    category: 'meat',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: '80% lean ground beef',
    synonyms: ['hamburger', 'ground meat', 'mince'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'beef-steak-lb',
    name: 'Beef Steak',
    category: 'meat',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'USDA Choice sirloin steak',
    synonyms: ['sirloin', 'steak', 'beef tenderloin'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'pork-chops-lb',
    name: 'Pork Chops',
    category: 'meat',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Bone-in pork chops',
    synonyms: ['pork', 'pork loin chops'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'bacon-lb',
    name: 'Bacon',
    category: 'meat',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'pack'],
    conversions: [
      { fromUnit: 'oz', toUnit: 'lb', factor: 0.0625 },
      { fromUnit: 'pack', toUnit: 'lb', factor: 1 },
    ],
    description: 'Sliced bacon, regular cut',
    synonyms: ['pork bacon', 'breakfast bacon'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'tuna-canned-oz',
    name: 'Canned Tuna',
    category: 'proteins',
    unitStandard: 'oz',
    acceptableAlternateUnits: ['lb', 'count'],
    conversions: [{ fromUnit: 'oz', toUnit: 'lb', factor: 0.0625 }],
    description: 'Canned tuna in water, 5 oz can',
    synonyms: ['tuna', 'canned fish'],
    sourceSeriesIds: ['bls-cpi'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'beans-dry-lb',
    name: 'Dried Beans',
    category: 'proteins',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['oz', 'kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Dried pinto or black beans',
    synonyms: ['pinto beans', 'black beans', 'legumes'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'apples-lb',
    name: 'Apples',
    category: 'produce',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['kg', 'count'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Red delicious or similar variety',
    synonyms: ['fresh apples', 'apple fruit'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'bananas-lb',
    name: 'Bananas',
    category: 'produce',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Fresh bananas',
    synonyms: ['fresh bananas'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'potatoes-lb',
    name: 'Potatoes',
    category: 'produce',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Russet or white potatoes',
    synonyms: ['russet potatoes', 'white potatoes'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'onions-lb',
    name: 'Onions',
    category: 'produce',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Yellow onions',
    synonyms: ['yellow onions', 'cooking onions'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'tomatoes-lb',
    name: 'Tomatoes',
    category: 'produce',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Fresh round tomatoes',
    synonyms: ['fresh tomatoes', 'field tomatoes'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'lettuce-head',
    name: 'Lettuce',
    category: 'produce',
    unitStandard: 'count',
    acceptableAlternateUnits: ['lb'],
    conversions: [{ fromUnit: 'count', toUnit: 'lb', factor: 1.5 }],
    description: 'Iceberg lettuce head',
    synonyms: ['iceberg lettuce', 'head lettuce'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'toilet-paper-roll',
    name: 'Toilet Paper',
    category: 'household',
    unitStandard: 'roll',
    acceptableAlternateUnits: ['pack'],
    conversions: [{ fromUnit: 'pack', toUnit: 'roll', factor: 12 }],
    description: 'Standard 2-ply toilet paper roll',
    synonyms: ['bathroom tissue', 'TP'],
    sourceSeriesIds: ['bls-cpi'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'paper-towels-roll',
    name: 'Paper Towels',
    category: 'household',
    unitStandard: 'roll',
    acceptableAlternateUnits: ['pack'],
    conversions: [{ fromUnit: 'pack', toUnit: 'roll', factor: 6 }],
    description: 'Standard paper towel roll',
    synonyms: ['kitchen towels', 'absorbent paper'],
    sourceSeriesIds: ['bls-cpi'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'detergent-oz',
    name: 'Laundry Detergent',
    category: 'household',
    unitStandard: 'oz',
    acceptableAlternateUnits: ['lb'],
    conversions: [{ fromUnit: 'oz', toUnit: 'lb', factor: 0.0625 }],
    description: 'Liquid laundry detergent, 100 oz bottle',
    synonyms: ['laundry soap', 'washing detergent'],
    sourceSeriesIds: ['bls-cpi'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'soap-bar',
    name: 'Bar Soap',
    category: 'household',
    unitStandard: 'count',
    acceptableAlternateUnits: ['oz'],
    conversions: [{ fromUnit: 'count', toUnit: 'oz', factor: 4 }],
    description: 'Bath bar soap',
    synonyms: ['bath soap', 'body soap'],
    sourceSeriesIds: ['bls-cpi'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'diapers-count',
    name: 'Diapers',
    category: 'household',
    unitStandard: 'count',
    acceptableAlternateUnits: ['pack'],
    conversions: [{ fromUnit: 'pack', toUnit: 'count', factor: 36 }],
    description: 'Disposable diapers, size 4',
    synonyms: ['baby diapers', 'disposable diapers'],
    sourceSeriesIds: ['bls-cpi'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'gasoline-gallon',
    name: 'Gasoline',
    category: 'fuel',
    unitStandard: 'gallon',
    acceptableAlternateUnits: ['liter'],
    conversions: [{ fromUnit: 'gallon', toUnit: 'liter', factor: 3.78541 }],
    description: 'Regular unleaded gasoline',
    synonyms: ['gas', 'petrol', 'fuel'],
    sourceSeriesIds: ['eia-petroleum'],
    regionCoverage: ['US-National', 'US-Midwest', 'US-Northeast', 'US-South', 'US-West'],
  },
  {
    id: 'diesel-gallon',
    name: 'Diesel Fuel',
    category: 'fuel',
    unitStandard: 'gallon',
    acceptableAlternateUnits: ['liter'],
    conversions: [{ fromUnit: 'gallon', toUnit: 'liter', factor: 3.78541 }],
    description: 'No. 2 diesel fuel',
    synonyms: ['diesel', 'diesel oil'],
    sourceSeriesIds: ['eia-petroleum'],
    regionCoverage: ['US-National', 'US-Midwest'],
  },
  {
    id: 'propane-gallon',
    name: 'Propane',
    category: 'fuel',
    unitStandard: 'gallon',
    acceptableAlternateUnits: ['liter'],
    conversions: [{ fromUnit: 'gallon', toUnit: 'liter', factor: 3.78541 }],
    description: 'Residential propane',
    synonyms: ['LP gas', 'liquefied petroleum'],
    sourceSeriesIds: ['eia-petroleum'],
    regionCoverage: ['US-National', 'US-Northeast'],
  },
  {
    id: 'heating-oil-gallon',
    name: 'Heating Oil',
    category: 'fuel',
    unitStandard: 'gallon',
    acceptableAlternateUnits: ['liter'],
    conversions: [{ fromUnit: 'gallon', toUnit: 'liter', factor: 3.78541 }],
    description: 'Residential heating oil (No. 2 fuel oil)',
    synonyms: ['fuel oil', 'heating fuel'],
    sourceSeriesIds: ['eia-petroleum'],
    regionCoverage: ['US-National', 'US-Northeast'],
  },
  {
    id: 'electricity-kWh',
    name: 'Electricity',
    category: 'utilities',
    unitStandard: 'kWh',
    acceptableAlternateUnits: [],
    conversions: [],
    description: 'Residential electricity per kilowatt-hour',
    synonyms: ['power', 'electric', 'kilowatt hour'],
    sourceSeriesIds: ['eia-electricity'],
    regionCoverage: ['US-National', 'US-Residential'],
  },
  {
    id: 'natural-gas-therm',
    name: 'Natural Gas',
    category: 'utilities',
    unitStandard: 'therm',
    acceptableAlternateUnits: ['ccf', 'kWh'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'therm' || c.toUnit === 'therm'),
    description: 'Residential natural gas per therm',
    synonyms: ['gas', 'natural gas utility'],
    sourceSeriesIds: ['eia-natural-gas'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'rent-index',
    name: 'Rent Index',
    category: 'utilities',
    unitStandard: 'count',
    acceptableAlternateUnits: [],
    conversions: [],
    description: 'CPI Rent of Primary Residence Index',
    synonyms: ['housing rent', 'rental index'],
    sourceSeriesIds: ['fred-housing'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'seeds-packet',
    name: 'Garden Seeds',
    category: 'inputs',
    unitStandard: 'count',
    acceptableAlternateUnits: ['oz'],
    conversions: [],
    description: 'Vegetable garden seed packet (tomato, lettuce, etc.)',
    synonyms: ['vegetable seeds', 'planting seeds'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'potting-soil-lb',
    name: 'Potting Soil',
    category: 'inputs',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'General purpose potting soil mix',
    synonyms: ['potting mix', 'garden soil'],
    sourceSeriesIds: ['bls-cpi'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'fertilizer-lb',
    name: 'Fertilizer',
    category: 'inputs',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['kg'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'General purpose 10-10-10 fertilizer',
    synonyms: ['plant food', 'garden fertilizer'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
  {
    id: 'feed-animal-lb',
    name: 'Animal Feed',
    category: 'inputs',
    unitStandard: 'lb',
    acceptableAlternateUnits: ['kg', 'bushel'],
    conversions: UNIT_CONVERSIONS.filter(c => c.fromUnit === 'lb' || c.toUnit === 'lb'),
    description: 'Livestock feed, corn or mixed grain',
    synonyms: ['livestock feed', 'chicken feed', 'grain feed'],
    sourceSeriesIds: ['usda-nass'],
    regionCoverage: ['US-National'],
  },
]

export const BASKET_TEMPLATES: BasketTemplate[] = [
  {
    id: 'family-4',
    name: 'Family of 4',
    description: '2 adults + 2 children weekly essentials basket',
    category: 'family-4',
    items: [
      { itemId: 'eggs-dozen', quantity: 2 },
      { itemId: 'milk-gallon', quantity: 3 },
      { itemId: 'bread-loaf', quantity: 2 },
      { itemId: 'cheese-lb', quantity: 1 },
      { itemId: 'butter-lb', quantity: 0.5 },
      { itemId: 'chicken-breast-lb', quantity: 3 },
      { itemId: 'ground-beef-lb', quantity: 2 },
      { itemId: 'rice-lb', quantity: 2 },
      { itemId: 'pasta-lb', quantity: 1.5 },
      { itemId: 'bananas-lb', quantity: 3 },
      { itemId: 'apples-lb', quantity: 2 },
      { itemId: 'potatoes-lb', quantity: 5 },
      { itemId: 'onions-lb', quantity: 2 },
      { itemId: 'tomatoes-lb', quantity: 2 },
      { itemId: 'gasoline-gallon', quantity: 20 },
    ],
    isPublic: true,
  },
  {
    id: 'single-adult',
    name: 'Single Adult',
    description: 'Single person weekly essentials basket',
    category: 'single-adult',
    items: [
      { itemId: 'eggs-dozen', quantity: 0.5 },
      { itemId: 'milk-gallon', quantity: 0.5 },
      { itemId: 'bread-loaf', quantity: 1 },
      { itemId: 'cheese-lb', quantity: 0.5 },
      { itemId: 'chicken-breast-lb', quantity: 1.5 },
      { itemId: 'rice-lb', quantity: 1 },
      { itemId: 'bananas-lb', quantity: 1 },
      { itemId: 'coffee-lb', quantity: 0.25 },
      { itemId: 'gasoline-gallon', quantity: 10 },
    ],
    isPublic: true,
  },
  {
    id: 'tradesperson',
    name: 'Tradesperson (Fuel-Heavy)',
    description: 'Work vehicle operator weekly basket',
    category: 'tradesperson',
    items: [
      { itemId: 'gasoline-gallon', quantity: 40 },
      { itemId: 'diesel-gallon', quantity: 30 },
      { itemId: 'eggs-dozen', quantity: 1 },
      { itemId: 'milk-gallon', quantity: 1 },
      { itemId: 'bread-loaf', quantity: 1 },
      { itemId: 'coffee-lb', quantity: 0.5 },
      { itemId: 'ground-beef-lb', quantity: 2 },
      { itemId: 'chicken-breast-lb', quantity: 2 },
    ],
    isPublic: true,
  },
]

export function getItemBySynonym(search: string): Item | undefined {
  const searchLower = search.toLowerCase().trim()
  return EXPANDED_ITEMS.find(
    item =>
      item.name.toLowerCase() === searchLower ||
      item.synonyms?.some(syn => syn.toLowerCase() === searchLower)
  )
}

export function getItemsByCategory(category: string): Item[] {
  return EXPANDED_ITEMS.filter(item => item.category === category)
}

export function getSourceById(sourceId: string): Source | undefined {
  return EXPANDED_SOURCES.find(s => s.id === sourceId)
}

export function convertUnit(value: number, fromUnit: UnitStandard, toUnit: UnitStandard): number {
  if (fromUnit === toUnit) return value
  
  const conversion = UNIT_CONVERSIONS.find(
    c => c.fromUnit === fromUnit && c.toUnit === toUnit
  )
  
  if (!conversion) {
    throw new Error(`No conversion found from ${fromUnit} to ${toUnit}`)
  }
  
  return value * conversion.factor
}
